# Generated by Django 2.2 on 2019-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20190423_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='sell_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date sold'),
        ),
    ]
