# Generated by Django 2.2 on 2019-04-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20190424_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='price',
            new_name='price_paid',
        ),
    ]
