# Generated by Django 2.2 on 2019-04-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_auto_20190425_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='current_price',
            field=models.FloatField(default=0, verbose_name='Current price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='price_paid',
            field=models.FloatField(verbose_name='Price paid'),
        ),
    ]
