# Generated by Django 2.2 on 2019-05-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_auto_20190503_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='asset_class',
            field=models.CharField(default='Stock', max_length=50, verbose_name='Asset class'),
        ),
    ]
