# Generated by Django 2.2 on 2019-05-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_auto_20190508_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='positive',
            field=models.BooleanField(default=False, verbose_name='positive'),
        ),
    ]
