# Generated by Django 2.2 on 2019-05-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0012_balancehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='sell_date',
        ),
        migrations.AlterField(
            model_name='trade',
            name='currency',
            field=models.CharField(choices=[('CHF', 'CHF : Swiss Franc'), ('EUR', 'EUR : Euro'), ('USD', 'USD : US Dollar')], default='USD', max_length=5, verbose_name='Currency'),
        ),
    ]
