# Generated by Django 2.2 on 2019-05-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_auto_20190509_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='action',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='USD', max_length=4, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='currency',
            field=models.CharField(choices=[('CHF', 'CHF : Swiss Franc'), ('EUR', 'EUR : Euro'), ('USD', 'USD : US Dollar')], default='USD', max_length=3, verbose_name='Currency'),
        ),
    ]
