# Generated by Django 2.2 on 2019-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_auto_20190509_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='action',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4, verbose_name='Action'),
        ),
    ]
