# Generated by Django 2.2 on 2019-05-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0016_auto_20190509_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='asset_class',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('GOLD', 'Gold'), ('LONG_BONDS', 'Long-term bonds'), ('MED_BONDS', 'Medium-term bonds'), ('SHORT_BONDS', 'Short-term bonds'), ('OTHER', 'Other')], default='STOCK', max_length=50, verbose_name='Asset class'),
        ),
    ]
