# Generated by Django 2.2 on 2019-05-10 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0017_auto_20190509_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset_class',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('GOLD', 'Gold'), ('CASH', 'Cash'), ('LONG_BONDS', 'Long-term bonds'), ('MED_BONDS', 'Medium-term bonds'), ('SHORT_BONDS', 'Short-term bonds'), ('OTHER', 'Other')], default='STOCK', max_length=50, verbose_name='Asset class'),
        ),
    ]
