# Generated by Django 2.2 on 2019-05-13 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0019_auto_20190510_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='AAPL', max_length=20, verbose_name='Ticker')),
                ('name', models.CharField(default='Apple', max_length=50, verbose_name='Name')),
                ('asset_class', models.CharField(choices=[('STOCK', 'Stock'), ('GOLD', 'Gold'), ('CASH', 'Cash'), ('LONG_BONDS', 'Long-term bonds'), ('MED_BONDS', 'Medium-term bonds'), ('SHORT_BONDS', 'Short-term bonds'), ('OTHER', 'Other')], default='STOCK', max_length=50, verbose_name='Asset class')),
                ('currency', models.CharField(choices=[('CHF', 'CHF : Swiss Franc'), ('EUR', 'EUR : Euro'), ('USD', 'USD : US Dollar')], default='USD', max_length=3, verbose_name='Currency')),
                ('number_of_shares', models.IntegerField(default=1, verbose_name='Number of shares')),
                ('user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
