# Generated by Django 2.2 on 2019-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0020_holding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='asset_class',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('GOLD', 'Gold'), ('CASH', 'Cash'), ('LONG_BONDS', 'Long-term bonds'), ('MED_BONDS', 'Medium-term bonds'), ('SHORT_BONDS', 'Short-term bonds'), ('CRYPTO', 'Cryptocurrencies'), ('OTHER', 'Other')], default='STOCK', max_length=50, verbose_name='Asset class'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset_class',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('GOLD', 'Gold'), ('CASH', 'Cash'), ('LONG_BONDS', 'Long-term bonds'), ('MED_BONDS', 'Medium-term bonds'), ('SHORT_BONDS', 'Short-term bonds'), ('CRYPTO', 'Cryptocurrencies'), ('OTHER', 'Other')], default='STOCK', max_length=50, verbose_name='Asset class'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='number_of_shares',
            field=models.FloatField(default=1, verbose_name='Number of shares'),
        ),
    ]
