# Generated by Django 2.2 on 2019-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0021_auto_20190514_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='price_paid',
        ),
        migrations.AddField(
            model_name='trade',
            name='price_per_share_paid',
            field=models.FloatField(default=1, verbose_name='Price paid (per share)'),
            preserve_default=False,
        ),
    ]
