# Generated by Django 2.2 on 2019-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0022_auto_20190514_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='total_value_chf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total value in CHF'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='number_of_shares',
            field=models.FloatField(default=1, verbose_name='Number of shares'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Last close value'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price_per_share_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price paid (per share)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total value'),
        ),
    ]
